export const MODULE_REGISTRY = [
  {
    id: 'order_management',
    name: 'Order Management',
    nameFr: 'Gestion des commandes',
    description: 'Orders, quotes, customers, calendar, and events.',
    descriptionFr: 'Commandes, devis, clients, calendrier et événements.',
    icon: 'ClipboardList',
    color: '#1a73e8',
    primaryRoute: '/orders',
    routes: ['/orders', '/customers', '/quotes', '/calendar', '/manager'],
    apiPrefixes: ['/api/orders', '/api/quotes', '/api/clients', '/api/calendar', '/api/manager'],
    permissions: [
      'view_orders', 'create_orders', 'edit_orders', 'delete_orders',
      'create_quotes', 'delete_quotes',
      'view_customers', 'edit_customers', 'delete_customers',
      'view_calendar', 'update_flow_status',
    ],
    subRoutes: [
      { href: '/orders',         label: 'Orders',    labelFr: 'Commandes',       permission: 'view_orders' },
      { href: '/quotes',         label: 'Quotes',    labelFr: 'Devis',           permission: null },
      { href: '/customers',      label: 'Customers', labelFr: 'Clients',         permission: 'view_customers' },
      { href: '/calendar',       label: 'Calendar',  labelFr: 'Calendrier',      permission: 'view_calendar' },
      { href: '/manager/events', label: 'My Events', labelFr: 'Mes événements',  permission: 'update_flow_status' },
    ],
    builtIn: true,
  },
  {
    id: 'inventory',
    name: 'Inventory',
    nameFr: 'Inventaire',
    description: 'Track kitchen equipment, stock levels, and supplier info.',
    descriptionFr: 'Suivi des équipements, niveaux de stock et informations fournisseurs.',
    icon: 'Warehouse',
    color: '#137333',
    primaryRoute: '/inventory',
    routes: ['/inventory'],
    apiPrefixes: ['/api/inventory'],
    permissions: ['view_inventory', 'manage_inventory'],
    builtIn: false,
  },
  {
    id: 'tasks',
    name: 'Tasks',
    nameFr: 'Tâches',
    description: 'Schedule and track follow-up tasks.',
    descriptionFr: 'Planifier et suivre les tâches de suivi.',
    icon: 'CheckSquare',
    color: '#1a73e8',
    primaryRoute: '/tasks',
    routes: ['/tasks'],
    apiPrefixes: ['/api/tasks'],
    permissions: ['view_tasks'],
    builtIn: false,
  },
];

export const MODULE_IDS = MODULE_REGISTRY.map(m => m.id);
