export const MODULE_REGISTRY = [
  {
    id: 'order_management',
    name: 'Order Management',
    nameFr: 'Gestion des commandes',
    description: 'Orders, quotes, customers, calendar, and events.',
    descriptionFr: 'Commandes, devis, clients, calendrier et événements.',
    icon: 'ClipboardList',
    color: '#1a73e8',
    primaryRoute: '/orders',
    routes: ['/orders', '/customers', '/quotes', '/calendar', '/manager'],
    apiPrefixes: ['/api/orders', '/api/quotes', '/api/clients', '/api/calendar', '/api/manager'],
    permissions: [
      'view_orders', 'create_orders', 'edit_orders', 'delete_orders',
      'create_quotes', 'delete_quotes',
      'view_customers', 'edit_customers', 'delete_customers',
      'view_calendar', 'update_flow_status',
    ],
    subRoutes: [
      { href: '/orders',         label: 'Orders',    labelFr: 'Commandes',       permission: 'view_orders' },
      { href: '/customers',      label: 'Customers', labelFr: 'Clients',         permission: 'view_customers' },
      { href: '/calendar',       label: 'Calendar',  labelFr: 'Calendrier',      permission: 'view_calendar' },
      { href: '/manager/events', label: 'My Events', labelFr: 'Mes événements',  permission: 'update_flow_status' },
    ],
    builtIn: true,
  },
  {
    id: 'inventory',
    name: 'Inventory',
    nameFr: 'Inventaire',
    description: 'Track kitchen equipment, stock levels, and supplier info.',
    descriptionFr: 'Suivi des équipements, niveaux de stock et informations fournisseurs.',
    icon: 'Warehouse',
    color: '#137333',
    primaryRoute: '/inventory',
    routes: ['/inventory'],
    apiPrefixes: ['/api/inventory'],
    permissions: ['view_inventory', 'manage_inventory', 'view_suppliers', 'edit_suppliers', 'delete_suppliers'],
    subRoutes: [
      { href: '/inventory',            label: 'Items',      labelFr: 'Articles',     permission: 'view_inventory' },
      { href: '/inventory/categories', label: 'Categories', labelFr: 'Catégories',   permission: 'manage_inventory' },
      { href: '/inventory/suppliers',  label: 'Suppliers',  labelFr: 'Fournisseurs', permission: 'view_suppliers' },
    ],
    builtIn: false,
  },
  {
    id: 'tasks',
    name: 'Tasks',
    nameFr: 'Tâches',
    description: 'Schedule and track follow-up tasks.',
    descriptionFr: 'Planifier et suivre les tâches de suivi.',
    icon: 'CheckSquare',
    color: '#1a73e8',
    primaryRoute: '/tasks',
    routes: ['/tasks'],
    apiPrefixes: ['/api/tasks'],
    permissions: ['view_tasks'],
    builtIn: false,
  },
  {
    id: 'laundry',
    name: 'Laundry',
    nameFr: 'Blanchisserie',
    description: 'Track linen batches sent to laundry, manage returns and write off losses.',
    descriptionFr: 'Suivi des envois de linge, gestion des retours et déduction des pertes.',
    icon: 'WashingMachine',
    color: '#0b8043',
    primaryRoute: '/laundry',
    routes: ['/laundry'],
    apiPrefixes: ['/api/laundry'],
    permissions: ['view_laundry', 'manage_laundry'],
    subRoutes: [
      { href: '/laundry', label: 'Batches', labelFr: 'Lots', permission: 'view_laundry' },
    ],
    builtIn: false,
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    nameFr: 'Cuisine',
    description: 'Manage kitchen stock, recipes, and ingredient costs.',
    descriptionFr: 'Gérez le stock cuisine, les recettes et les coûts d\'ingrédients.',
    icon: 'ChefHat',
    color: '#e37400',
    primaryRoute: '/kitchen',
    routes: ['/kitchen'],
    apiPrefixes: ['/api/kitchen'],
    permissions: ['view_kitchen', 'manage_kitchen'],
    subRoutes: [
      { href: '/kitchen/stock',   label: 'Stock',   labelFr: 'Stock',    permission: 'view_kitchen' },
      { href: '/kitchen/recipes', label: 'Recipes', labelFr: 'Recettes', permission: 'view_kitchen' },
    ],
    builtIn: false,
  },
];

export const MODULE_IDS = MODULE_REGISTRY.map(m => m.id);
